#pragma once

#define TERRAIN_SIZE 256
#define TERRAIN_INTERVAL 4.0f
#define TERRAIN_VERTEX_COUNT (TERRAIN_SIZE/TERRAIN_INTERVAL+1)

#define MAX_TERRAIN_TEXTURES 4
#define MAX_TERRAIN_TEXTURES_STR "4"
#define TERRAIN_BLENDMAP_COUNT (MAX_TERRAIN_TEXTURES/4 + ((MAX_TERRAIN_TEXTURES%4 == 0) ? 0 : 1))